### PR TITLE
move function types to flowkit

### PR DESCRIPTION
**Pull request by FelixKuhnAnsys**

### CODE REVIEW

**Review by RobPasMue — CHANGES_REQUESTED** [review]
The goal of the sharedtypes repo was to host these common structs. Why moving them back again?

**Comment by FelixKuhnAnsys** [comment]
> The goal of the sharedtypes repo was to host these common structs. Why moving them back again?

flowkit is currently not setup to support external struct types in its inputs and outputs due to the way the naming of the types is extractacted. i'm not sure how easy it is to fix this, but you're right, it is probably the more sensible way to fix this instead of temporarily moving the types back before doing so... i'll investigate

**Comment by RobPasMue** [comment]
> flowkit is currently not setup to support external struct types in its inputs and outputs due to the way the naming of the types is extractacted. i'm not sure how easy it is to fix this, but you're right, it is probably the more sensible way to fix this instead of temporarily moving the types back before doing so... i'll investigate

I'd recommend to dedicate some time to try and figure this out rather than move them back...

**Comment by FelixKuhnAnsys** [comment]
> > flowkit is currently not setup to support external struct types in its inputs and outputs due to the way the naming of the types is extractacted. i'm not sure how easy it is to fix this, but you're right, it is probably the more sensible way to fix this instead of temporarily moving the types back before doing so... i'll investigate
> 
> I'd recommend to dedicate some time to try and figure this out rather than move

**Pull request closed without merging**
